# Generated by Django 5.2.7 on 2025-10-19 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brand", "0002_alter_brand_created_at_alter_brand_updated_at"),
        ("category", "0002_alter_category_created_at_alter_category_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "serie_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("quantity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Products",
                        to="brand.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Products",
                        to="category.category",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
