# Generated by Django 5.2.7 on 2025-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outflows", "0002_alter_outflows_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflows",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="outflows",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
