# Generated by Django 5.2.7 on 2025-10-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outflows", "0003_alter_outflows_created_at_alter_outflows_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflows",
            name="created_at",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="outflows",
            name="updated_at",
            field=models.TimeField(auto_now=True),
        ),
    ]
