# Generated by Django 5.2.7 on 2025-10-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=400)),
                ("created_at", models.TimeField(auto_now_add=True)),
                ("updated_at", models.TimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
