# Generated by Django 5.2.7 on 2025-10-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inflow",
            options={"ordering": ["-created_at"]},
        ),
    ]
